config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  get 'pages/features'

  get 'pages/demo'

  get 'pages/contact'
  
  root 'pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def features
  end

  def demo
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer" role="contentinfo">
		<a href="#" class="gotop js-gotop"><i class="icon-arrow-up2"></i></a>
		<div class="container">
			<div class="">
				<div class="col-md-12 text-center">
					<p>&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a></p>
					
				</div>
			</div>
			<div class="row">
				<div class="col-md-12 text-center">
					<ul class="social social-circle">
						<li><a href="#"><i class="icon-twitter"></i></a></li>
						<li><a href="#"><i class="icon-facebook"></i></a></li>
						<li><a href="#"><i class="icon-youtube"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>

app/views/layouts/_header.html.erb
<header role="banner" id="fh5co-header">
			<div class="container">
				<!-- <div class="row"> -->
			    <nav class="navbar navbar-default">
		        <div class="navbar-header">
		        	<!-- Mobile Toggle Menu Button -->
					<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"><i></i></a>
		         <%= link_to 'Resty', root_path, class: "navbar-brand" %>
		         	
		         
		        </div>
		        <div id="navbar" class="navbar-collapse collapse">
		          <ul class="nav navbar-nav navbar-right">
		            <li class="active"><a href="#"><span>Home</span></a></li>
		            <li>
		            	<%= link_to pages_features_path do %>
		            		<span>Features</span>
		            	<% end %>
		            </li>
		            <li>
		            	<%= link_to pages_demo_path do %>
		            		<span>Demo</span>
		            	<% end %>
		            </li>
		            <li>
		            	<%= link_to '#' do %>
		            		<span>Pricing</span>
		            	<% end %>
		            </li>
		            <li>
		            	<%= link_to pages_contact_path do %>
		            		<span>Contact</span>
		            	<% end %>
		            </li>
		          </ul>
		        </div>
			    </nav>
			  <!-- </div> -->
		  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="http://fonts.googleapis.com/css?family=Questrial" rel="stylesheet" type="text/css">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/_intro.html.erb
<section id="fh5co-home" data-section="home" style="background-image: url(<%= image_path 'full_image_1_3.jpg' %>);" data-stellar-background-ratio="0.5">
		<div class="gradient"></div>
		<div class="container">
			<div class="text-wrap">
				<div class="text-inner">
					<div class="row">
						<div class="col-md-8 col-md-offset-2">
							<h1 class="to-animate">Best websites for restaurants.</h1>
							<h2 class="to-animate">Beaufitul. Efficient. Works on mobile phones. Affordable.  <a href="http://thecookiedining.com/" target="_blank" title="Integrated online ordering">Online ordering supported.</a> <a href="http://thecookiedining.com" target="_blank">Mobile apps available.</a></h2>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="slant"></div>
	</section>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/demo.html.erb
<h1>Pages#demo</h1>
<p>Find me in app/views/pages/demo.html.erb</p>

app/views/pages/features.html.erb
<h1>Pages#features</h1>
<p>Find me in app/views/pages/features.html.erb</p>